# Generated by Django 6.0.5 on 2026-05-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='meses_duracion',
            field=models.IntegerField(default=1, help_text='Duración del crédito en meses'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='interes_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='numero_cuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='porcentaje_interes',
            field=models.IntegerField(help_text='Porcentaje de interés mensual (ej. 16)'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='saldo_restante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='total_deuda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='valor_cuota_recomendada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
